# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

range_boundaries <- function(cidr) {
    .Call(`_iptools2_range_boundaries`, cidr)
}

