# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Retrieve range boundaries for a character vector of IPv4/IPv6 CIDRs
#'
#' @param cidr a character vector of IPv4/IPv6 CIDRs
#' @return data frame with original input, canonical CIDR, start/end (chr) of range and number of hosts.
#' @note the `n_hosts` column is a numeric vector since R cannot handle 128-bit integers easily and
#'       v4 & v6 are co-mingled.
#' @export
#' @examples
#' range_boundaries(
#'   c("2001:4801::/32", "2001:0db8::/127", "10.1.10.0/24", "2001:0db8::/119", "wat")
#' )
range_boundaries <- function(cidr) {
    .Call(`_iptools2_range_boundaries`, cidr)
}

